from typing import Any, Optional

from .core import DataFrame, Series, Index

def assert_extension_array_equal(left: Any, right: Any,  check_dtype: bool = ..., check_less_precise: bool = ..., check_exact: bool = ...) -> None: ...
def assert_frame_equal(left: DataFrame, right: DataFrame, check_like: Optional[bool] = ...) -> None: ...
def assert_index_equal(left: Index, right: Index) -> None: ...
def assert_series_equal(left: Series[_DType], right: Series[_DType]) -> None: ...
